services:
  - type: web
    name: sitec-wordpress
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: dpg-d7bbs2k9c44c73akdvvg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: sitec_4k8b
      - key: DB_USER
        value: sitec
      - key: DB_PASSWORD
        value: 09hUQOGbvvNVuImfEUBOABWFnlYfPR8X
      - key: DB_CHARSET
        value: utf8
      - key: WP_HOME
        value: https://sitec-wordpress.onrender.com
      - key: WP_SITEURL
        value: https://sitec-wordpress.onrender.com
      - key: DISABLE_WP_CRON
        value: "1"
      - key: FORCE_SSL_ADMIN
        value: "1"
