services:
  - type: web
    name: sitec-wordpress
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: WP_HOME
        value: https://sitec-wordpress.onrender.com
      - key: WP_SITEURL
        value: https://sitec-wordpress.onrender.com
      - key: DISABLE_WP_CRON
        value: "1"
      - key: FORCE_SSL_ADMIN
        value: "1"
