services:
  - type: web
    name: sitec-wordpress
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: 4cn58h.h.filess.io
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: sitec_finalthose
      - key: DB_USER
        value: sitec_finalthose
      - key: DB_PASSWORD
        value: dfb50b40271eda1b9317e6fed5b5989846de3a97
      - key: WP_HOME
        value: https://sitec-wordpress.onrender.com
      - key: WP_SITEURL
        value: https://sitec-wordpress.onrender.com
      - key: DISABLE_WP_CRON
        value: "1"
      - key: FORCE_SSL_ADMIN
        value: "1"
